// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxXVNLJy2QvcKcavCofz4HJxnux4-riBI',
    appId: '1:903575549704:web:aa052e9e004cd3f400debd',
    messagingSenderId: '903575549704',
    projectId: 'soundboard-3407f',
    authDomain: 'soundboard-3407f.firebaseapp.com',
    storageBucket: 'soundboard-3407f.firebasestorage.app',
    measurementId: 'G-VQYR6542HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydGVCvu4Cnp8Ro0lQuCVBgWULeNoQZzQ',
    appId: '1:903575549704:android:0b4dd5438ea608a400debd',
    messagingSenderId: '903575549704',
    projectId: 'soundboard-3407f',
    storageBucket: 'soundboard-3407f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEP9Fm7aU2Mjvz5GAZcfMolNPOrHhLx4k',
    appId: '1:903575549704:ios:159d6ae6b99f08ee00debd',
    messagingSenderId: '903575549704',
    projectId: 'soundboard-3407f',
    storageBucket: 'soundboard-3407f.firebasestorage.app',
    iosBundleId: 'com.example.soundboard0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEP9Fm7aU2Mjvz5GAZcfMolNPOrHhLx4k',
    appId: '1:903575549704:ios:e579306e1ef2ce3900debd',
    messagingSenderId: '903575549704',
    projectId: 'soundboard-3407f',
    storageBucket: 'soundboard-3407f.firebasestorage.app',
    iosBundleId: 'com.example.soundboard0.RunnerTests',
  );
}
